# Generated by Django 5.2.1 on 2025-09-04 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video1', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('video3', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
