# Generated by Django 5.2.1 on 2025-06-23 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video1', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('video2', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('video3', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.post')),
                ('repost_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post')),
                ('views', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
