# Generated by Django 5.2.1 on 2025-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0003_alter_section_tag'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_sections',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='constitution.section'),
        ),
    ]
