# Generated by Django 5.2.1 on 2025-07-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_reason_poll'),
        ('posts', '0002_initial'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.poll'),
        ),
        migrations.AddField(
            model_name='post',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey'),
        ),
    ]
