# Generated by Django 5.2.7 on 2025-12-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_helpful_votes', models.ManyToManyField(blank=True, related_name='is_helpful_votes', to=settings.AUTH_USER_MODEL)),
                ('is_not_helpful_votes', models.ManyToManyField(blank=True, related_name='is_not_helpful_votes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notes', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
