# Generated by Django 5.2.1 on 2025-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tagged_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_edited',
        ),
    ]
