# Generated by Django 5.2.1 on 2025-09-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('live', '0001_initial'),
        ('petition', '0002_initial'),
        ('posts', '0004_remove_post_is_edited'),
        ('survey', '0003_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='live.meeting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ballot.ballot'),
        ),
        migrations.AlterField(
            model_name='post',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='petition.petition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='survey.survey'),
        ),
    ]
