# Generated by Django 5.2.1 on 2025-07-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
    ]
