# Generated by Django 5.2.7 on 2026-01-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_community_note_of_post_downvotes_post_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6',
        ),
    ]
