# Generated by Django 5.2.1 on 2025-07-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_publishedpost_reply_repost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedPost',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
