# Generated by Django 6.0.1 on 2026-03-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_sections',
        ),
    ]
