# Generated by Django 5.2.1 on 2025-07-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_publishedpost_delete_reply_delete_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reason',
            new_name='issue',
        ),
    ]
