# Generated by Django 5.2.1 on 2025-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
