# Generated by Django 5.2.1 on 2025-05-11 19:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('website', models.URLField(blank=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_counties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
                'db_table': 'County',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_constituencies', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='country.county')),
            ],
            options={
                'verbose_name': 'constituency',
                'verbose_name_plural': 'constituencies',
                'db_table': 'Constituency',
                'ordering': ['name'],
            },
        ),
    ]
