# Generated by Django 5.2.1 on 2025-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='display name'),
        ),
    ]
