# Generated by Django 5.2.7 on 2025-10-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_status_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
