# Generated by Django 6.0.1 on 2026-01-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('users', '0003_customuser_is_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.county'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.ward'),
        ),
    ]
