# Generated by Django 5.2.1 on 2025-06-21 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='muted',
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='muted',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
