# Generated by Django 6.0.1 on 2026-03-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_constituency_customuser_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_representative',
        ),
    ]
