# Generated by Django 5.2.1 on 2025-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.IntegerField(default=0, verbose_name='ID number'),
            preserve_default=False,
        ),
    ]
