# Generated by Django 5.2.1 on 2025-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.IntegerField(unique=True, verbose_name='ID number'),
        ),
    ]
