# Generated by Django 5.2.1 on 2025-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='cover_photos/default.jpg', upload_to='cover_photos/'),
        ),
    ]
