# Generated by Django 6.0.4 on 2026-05-01 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaking_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
