# Generated by Django 6.0.4 on 2026-05-21 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
