# Generated by Django 6.0.4 on 2026-05-02 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_speakers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaker_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
