# Generated by Django 6.0.4 on 2026-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_live_stream',
            field=models.BooleanField(default=False),
        ),
    ]
