# Generated by Django 6.0.4 on 2026-05-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meeting_description_alter_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
    ]
