# Generated by Django 6.0.4 on 2026-05-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_remove_meeting_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='co_hosts',
            field=models.ManyToManyField(related_name='host_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpeakerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_requests', to='meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SpeakerRequest',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
