# Generated by Django 6.0.4 on 2026-05-15 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_meeting_co_hosts_speakerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='co_hosts',
            field=models.ManyToManyField(blank=True, related_name='host_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
