services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 web:
   build: .
   container_name: democracy
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
#     LOGLEVEL: ${DJANGO_LOGLEVEL}
     ALLOWED_HOSTS: ${ALLOWED_HOSTS}

     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_HOST: "db" # The postgres database no longer runs at localhost. "db" is the name of the database container.
     DB_PORT: ${DB_PORT}
   env_file:
     - .env
volumes:
   postgres_data: