# Generated by Django 6.0.4 on 2026-04-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(blank=True, default='', max_length=5)),
                ('text', models.TextField()),
                ('is_title', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='constitution.section')),
            ],
            options={
                'db_table': 'Section',
                'ordering': ['id'],
            },
        ),
    ]
