# Generated by Django 6.0.1 on 2026-04-04 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('numeral', models.CharField(blank=True, default='', max_length=5)),
                ('text', models.TextField()),
                ('is_title', models.BooleanField()),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='constitution_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsections', to='constitution.section')),
            ],
            options={
                'db_table': 'Section',
                'ordering': ['id', 'parent__position', 'position'],
            },
        ),
    ]
