# Generated by Django 6.0.4 on 2026-08-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(blank=True, default='', max_length=5)),
                ('text', models.TextField()),
                ('is_title', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='constitution.section')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'db_table': 'Section',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['parent_id'], name='Section_parent__b2ab95_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='section_parent_not_self')],
            },
        ),
    ]
