# Generated by Django 6.0.4 on 2026-08-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
    ]
