# Generated by Django 6.0.4 on 2026-08-11 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['parent_id', 'id'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['parent_id'], name='Section_parent__b2ab95_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='section_parent_not_self'),
        ),
    ]
