# Generated by Django 6.0.1 on 2026-04-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='constitution.section'),
        ),
    ]
