# Generated by Django 6.0.4 on 2026-09-08 09:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='section',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='section_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('text'), name='gin_trgm_ops'), name='section_text_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('numeral'), name='gin_trgm_ops'), name='section_numeral_trgm_idx'),
        ),
    ]
