# Generated by Django 5.2.1 on 2025-08-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_notifications', models.BooleanField(default=True)),
                ('allow_follow_notifications', models.BooleanField(default=True)),
                ('allow_tag_notifications', models.BooleanField(default=True)),
                ('allow_like_notifications', models.BooleanField(default=True)),
                ('allow_reply_notifications', models.BooleanField(default=True)),
                ('allow_repost_notifications', models.BooleanField(default=True)),
                ('allow_message_notifications', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ballot.ballot')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-id'],
            },
        ),
    ]
