# Generated by Django 5.2.1 on 2025-09-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petition.petition'),
        ),
    ]
