# Generated by Django 5.2.1 on 2025-08-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
    ]
