# Generated by Django 5.2.1 on 2025-08-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_initial'),
        ('petition', '0003_alter_petition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petition.petition'),
        ),
    ]
