# Generated by Django 5.2.1 on 2025-08-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_options'),
        ('posts', '0010_alter_post_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_notifications', models.BooleanField(default=True)),
                ('follow_notifications', models.BooleanField(default=True)),
                ('tag_notifications', models.BooleanField(default=True)),
                ('like_notifications', models.BooleanField(default=True)),
                ('reply_notifications', models.BooleanField(default=True)),
                ('repost_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_notifications', to=settings.AUTH_USER_MODEL)),
                ('muted_posts', models.ManyToManyField(blank=True, to='posts.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Preferences',
            },
        ),
    ]
