# Generated by Django 5.2.1 on 2025-09-04 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0004_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferences',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='followers_notified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferences',
            name='muted_posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
