# Generated by Django 5.2.1 on 2025-09-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
        ('notification', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live.meeting'),
        ),
    ]
