# Generated by Django 5.2.1 on 2025-08-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='follow_notifications',
            new_name='allow_follow_notifications',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='like_notifications',
            new_name='allow_like_notifications',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='message_notifications',
            new_name='allow_message_notifications',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='reply_notifications',
            new_name='allow_reply_notifications',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='repost_notifications',
            new_name='allow_repost_notifications',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='tag_notifications',
            new_name='allow_tag_notifications',
        ),
    ]
