# Generated by Django 5.2.1 on 2025-08-09 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_rename_follow_notifications_preferences_allow_follow_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='followers_notified', to=settings.AUTH_USER_MODEL),
        ),
    ]
