# Generated by Django 6.0.4 on 2026-04-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_options_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_options', through='ballot.OptionVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reason',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='reason',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='optionvote',
            unique_together={('user', 'option')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['ballot'], name='Option_ballot__c67898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('ballot', 'text')},
        ),
        migrations.AddIndex(
            model_name='reason',
            index=models.Index(fields=['ballot', 'user'], name='Reason_ballot__638340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reason',
            unique_together={('ballot', 'user')},
        ),
    ]
