# Generated by Django 6.0.4 on 2026-08-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='ballotvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ballot.option'),
        ),
        migrations.AddField(
            model_name='reason',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='reason',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='ballot.option'),
        ),
        migrations.AddField(
            model_name='reason',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reasoncluster',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_clusters', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='reasoncluster',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_clusters', to='ballot.option'),
        ),
        migrations.AddField(
            model_name='reasonembedding',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_embeddings', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='reasonembedding',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_embeddings', to='ballot.option'),
        ),
        migrations.AddField(
            model_name='reasonembedding',
            name='reason',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='ballot.reason'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['end_time', 'is_active'], name='Ballot_end_tim_4275d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ballot_end_time_after_start_time', violation_error_message='The end time must be after the start time.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('constituency__isnull', False), _connector='OR'), name='ballot_ward_requires_constituency', violation_error_message='A ward requires a constituency.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('county__isnull', False), _connector='OR'), name='ballot_ward_requires_county', violation_error_message='A ward requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('constituency__isnull', True), ('county__isnull', False), _connector='OR'), name='ballot_constituency_requires_county', violation_error_message='A constituency requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('ballot', 'text'), name='unique_option_text_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='ballotvote',
            constraint=models.UniqueConstraint(fields=('user', 'ballot'), name='unique_ballot_vote_per_user_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='reason',
            constraint=models.UniqueConstraint(fields=('ballot', 'user'), name='unique_reason_per_user_per_ballot'),
        ),
        migrations.AddIndex(
            model_name='reasoncluster',
            index=models.Index(fields=['ballot', 'option'], name='ReasonClust_ballot__a95246_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoncluster',
            index=models.Index(fields=['ballot', 'option', 'size'], name='ReasonClust_ballot__448b42_idx'),
        ),
        migrations.AddConstraint(
            model_name='reasoncluster',
            constraint=models.UniqueConstraint(fields=('ballot', 'option', 'external_cluster_id'), name='unique_ballot_option_cluster'),
        ),
        migrations.AddIndex(
            model_name='reasonembedding',
            index=models.Index(fields=['ballot', 'option'], name='ReasonEmbed_ballot__8ebdfc_idx'),
        ),
    ]
