# Generated by Django 6.0.4 on 2026-08-11 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_options_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_options', through='ballot.OptionVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reason',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='ballot.ballot'),
        ),
        migrations.AddField(
            model_name='reason',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ballot_end_time_after_start_time', violation_error_message='The end time must be after the start time.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('constituency__isnull', False), _connector='OR'), name='ballot_ward_requires_constituency', violation_error_message='A ward requires a constituency.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('county__isnull', False), _connector='OR'), name='ballot_ward_requires_county', violation_error_message='A ward requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('constituency__isnull', True), ('county__isnull', False), _connector='OR'), name='ballot_constituency_requires_county', violation_error_message='A constituency requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='optionvote',
            constraint=models.UniqueConstraint(fields=('user', 'option'), name='unique_vote_per_user_per_option'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['ballot'], name='Option_ballot__c67898_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('ballot', 'text'), name='unique_option_text_per_ballot'),
        ),
        migrations.AddIndex(
            model_name='reason',
            index=models.Index(fields=['ballot', 'user'], name='Reason_ballot__638340_idx'),
        ),
        migrations.AddConstraint(
            model_name='reason',
            constraint=models.UniqueConstraint(fields=('ballot', 'user'), name='unique_reason_per_user_per_ballot'),
        ),
    ]
