# Generated by Django 6.0.1 on 2026-04-08 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reason',
            unique_together={('ballot', 'user')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['ballot'], name='Option_ballot__c67898_idx'),
        ),
        migrations.AddIndex(
            model_name='reason',
            index=models.Index(fields=['ballot', 'user'], name='Reason_ballot__638340_idx'),
        ),
    ]
