# Generated by Django 6.0.4 on 2026-08-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('reasons_total', models.PositiveIntegerField(default=0)),
                ('reasons_processed', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ballot Summary',
                'verbose_name_plural': 'Ballot Summaries',
                'db_table': 'BallotSummary',
            },
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['end_time', 'is_active'], name='Ballot_end_tim_4275d8_idx'),
        ),
        migrations.AddField(
            model_name='ballotsummary',
            name='ballot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='ballot.ballot'),
        ),
    ]
