# Generated by Django 6.0.4 on 2026-04-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_alter_option_votes_alter_reason_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='votes',
        ),
    ]
