# Generated by Django 6.0.4 on 2026-04-13 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_remove_option_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_through', to='ballot.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_options_through', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option Vote',
                'verbose_name_plural': 'Option Votes',
                'db_table': 'OptionVote',
                'ordering': ['-voted_at'],
                'unique_together': {('user', 'option')},
            },
        ),
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_options', through='ballot.OptionVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
