# Generated by Django 5.2.1 on 2025-07-08 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0004_alter_reason_poll'),
        ('posts', '0006_delete_publishedpost_delete_reply_delete_repost'),
        ('survey', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='poll.poll')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='posts.post')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['-created_at'],
            },
        ),
    ]
