# Generated by Django 5.2.1 on 2025-07-26 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('poll', '0004_alter_reason_poll'),
        ('posts', '0009_post_tagged_users'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='survey.survey'),
        ),
    ]
