# Generated by Django 5.2.1 on 2025-08-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('petition', '0003_alter_petition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='petition.petition'),
        ),
    ]
