# Generated by Django 6.0.1 on 2026-03-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_ballot_constituency_ballot_county_ballot_ward'),
        ('chat', '0002_initial'),
        ('petition', '0004_petition_is_open'),
        ('posts', '0007_remove_post_tagged_sections'),
        ('survey', '0003_survey_constituency_survey_county_survey_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='ballot.ballot'),
        ),
        migrations.AlterField(
            model_name='message',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='petition.petition'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='survey.survey'),
        ),
    ]
