# Generated by Django 5.2.1 on 2025-08-21 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='petitions/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='petitions/videos/')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL)),
                ('supporters', models.ManyToManyField(blank=True, related_name='supported_petitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Petition',
                'ordering': ['-start_time'],
            },
        ),
    ]
