# Generated by Django 5.2.1 on 2025-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='petitions/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='petitions/videos/')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Petition',
                'ordering': ['-start_time'],
            },
        ),
    ]
