# Generated by Django 5.2.1 on 2025-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='petitions/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='petitions/videos/')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'Petition',
                'ordering': ['-created_at'],
            },
        ),
    ]
