# Generated by Django 5.2.1 on 2025-09-25 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
