# Generated by Django 5.2.1 on 2025-08-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='end_time',
        ),
    ]
