# Generated by Django 6.0.1 on 2026-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_petition_constituency_petition_county_petition_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='open'),
        ),
    ]
