# Generated by Django 5.2.1 on 2025-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_alter_petition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
