"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import sentry_sdk
from decouple import config, Csv
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="NO-SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=True)

MODE = config('MODE', default="dev")

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Sentry
sentry_sdk.init(
    dsn=config('SENTRY_DSN'),
    integrations=[DjangoIntegration()],
    traces_sample_rate=0.2,
    environment=MODE,
    release=config("SENTRY_RELEASE"),
)

if os.name == 'nt':
    OSGEO4W = r"C:\OSGeo4W"
    # import platform
    # if '64' in platform.architecture()[0]:
    #     OSGEO4W += "64"
    assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    os.environ['GDAL_DATA'] = OSGEO4W + r"\share\gdal"
    os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']

if os.name == 'nt':
    GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal309.dll'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.contenttypes',
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.gis',
    'django.contrib.postgres',
    'django.contrib.humanize',
    'taggit',
    'apps.geo',
    'apps.users',
    'apps.survey',
    'apps.ballot',
    'apps.posts',
    'apps.petition',
    'apps.chat',
    'apps.notification',
    'apps.constitution',
    'apps.broadcast',
    'apps.recommendations',
    'rest_framework',
    'rest_framework_gis',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'fcm_django',
    'corsheaders',
    'django_filters',
    'nested_admin',
    'leaflet',
    'django_celery_results',
    'django_celery_beat',
    'storages',
]

if MODE == 'dev' and DEBUG:
    DATA_UPLOAD_MAX_NUMBER_FIELDS = None

AUTH_USER_MODEL = 'users.User'

# Grappelli configs
GRAPPELLI_ADMIN_TITLE = 'Democracy'
GRAPPELLI_SWITCH_USER = True
GRAPPELLI_CLEAN_INPUT_TYPES = True
GRAPPELLI_INDEX_DASHBOARD = 'project.dashboard.CustomIndexDashboard'

SITE_ID = 1

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = config('ORIGINS', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('ORIGINS', cast=Csv())
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

ASGI_APPLICATION = 'project.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'NON_FIELD_ERRORS_KEY': 'error',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-uk'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

REDIS_URL = "redis://redis:6379"
REDIS_POOL_MAX_CONNECTIONS = 100

# Firebase Admin
import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)

FCM_DJANGO_SETTINGS = {
    "DEFAULT_FIREBASE_APP": None,
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": True,
}

# Celery Configuration Options
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# django-celery-results
CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# AWS
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
# AWS_S3_SIGNATURE_VERSION = config('AWS_S3_SIGNATURE_VERSION')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_URL = '/static/'

STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AGORA_APP_ID = config('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = config('AGORA_APP_CERTIFICATE')
AGORA_CUSTOMER_ID = config('AGORA_CUSTOMER_ID')
AGORA_CUSTOMER_SECRET = config('AGORA_CUSTOMER_SECRET')
BROADCAST_PERIOD = 60 * 60  # 1 hour
BROADCAST_PARTICIPANT_TTL = 60 * 60 * 2  # 2 hours
BROADCAST_MAX_SPEAKERS = 10
BROADCAST_MAX_PAGE_SIZE = 100
# Timeout for Agora API requests.
# Tuple format: (connect timeout, read timeout)
AGORA_API_TIMEOUT = (5, 30)

# How many active recording sessions to check per task run.
RECORDING_STATUS_BATCH_SIZE = 50

# Small delay between Agora queries to avoid rate limiting.
RECORDING_STATUS_SLEEP_SECONDS = 0.1

# Mark recording sessions as error if active longer than this many hours.
# Set to 0 to disable.
STALE_RECORDING_SESSION_HOURS = 24


CHAT_MAX_ASSETS_PER_MESSAGE = 10
CHAT_MAX_UPLOAD_SIZE = 25 * 1024 * 1024  # 25 MB
CHAT_ALLOWED_CONTENT_TYPES = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "video/mp4",
    "audio/mpeg",
    "application/pdf",
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "media",  # Files go into /media/ folder in R2
            "querystring_auth": False,  # Set to True for private, expiring URLs
            "file_overwrite": False,  # Prevents users from overwriting existing uploads
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        "OPTIONS": {
            "location": "static",
            "default_acl": "public-read",
            "querystring_auth": False,  # Vital for publicly caching static assets
            "file_overwrite": True,
        },
    },
}

# Recommendation System Settings
POST_RECOMMENDER_CONFIG = {
    "CACHE": {
        "KEY_PREFIX": "user_recs_",
        "TIMEOUT": 60 * 30,
        "TRENDING_TIMEOUT": 600,
    },

    "RECOMMENDATIONS": {
        "DEFAULT_LIMIT": 20,
        "SCORED_LIMIT": 50,
        "DIVERSITY_FACTOR": 0.08,
    },

    "TRENDING_POSTS": {
        "DEFAULT_LIMIT": 20,
        "WINDOW_DAYS": 365,
        "WEIGHTS": {
            "likes": 3.0,
            "bookmarks": 3.0,
            "clicks": 2.0,
            "views": 1.0,
            "reposts": 5.0,
        },
    },

    "TRENDING_HASHTAGS": {
        "DEFAULT_LIMIT": 10,
        "WINDOW_DAYS": 7,
        "CACHE_TIMEOUT": 600,
    },

    "TRENDING_WORDS": {
        "DEFAULT_LIMIT": 15,
        "WINDOW_DAYS": 7,
        "MIN_FREQUENCY": 3,
        "MIN_WORD_LENGTH": 4,
        "CACHE_TIMEOUT": 600,

        "STOP_WORDS": [
            "the", "and", "or", "but", "in", "on", "at", "to", "for",
            "of", "with", "by", "from", "up", "about", "into", "over",
            "after", "this", "that", "these", "those", "is", "are",
            "was", "were", "be", "been", "being", "have", "has", "had",
            "do", "does", "did", "will", "would", "shall", "should",
            "can", "could", "may", "might", "must", "a", "an", "i",
            "you", "he", "she", "it", "we", "they", "me", "him", "her",
            "us", "them", "my", "your", "his", "its", "our", "their",
            "not", "no", "yes", "if", "then", "else", "when", "where",
            "how", "what", "who", "which", "why", "all", "any", "both",
            "each", "few", "more", "most", "other", "some", "such",
            "than", "too", "very", "just", "now", "so", "as", "like",
            "get", "got", "make", "made", "one", "two", "three", "also",
            "because", "however", "although", "still", "even", "back",
            "well", "say",
        ],

        "EXCLUDED_WORDS": [
            "http",
            "https",
            "www",
            "com",
            "net",
            "org",
            "gov",
            "edu",
            "io",
            "co",
            "uk",
            "ca",
            "au",
            "de",
            "fr",
            "png",
            "jpg",
            "jpeg",
            "gif",
            "pdf",
            "html",
            "php",
            "asp",
            "email",
            "mailto",
            "utm",
            "fbclid",
            "gclid",
        ],
    },

    "TRENDING_TOPICS": {
        "DEFAULT_LIMIT": 30,
        "WINDOW_DAYS": 7,
    },

    # Final recommendation score weights
    "SCORING_WEIGHTS": {
        "location": 0.25,
        "content_type": 0.18,
        "media": 0.12,
        "following": 0.15,
        "profile_visit": 0.10,
        "click": 0.08,
        "engagement": 0.07,
        "freshness": 0.10,
        "similarity": 0.05,
        "note_quality": 0.02,
    },

    # Engagement score used inside main recommendations
    "ENGAGEMENT_WEIGHTS": {
        "likes": 2.0,
        "bookmarks": 2.0,
        "views": 0.5,
        "reposts": 3.0,
    },

    "LOCATION_SCORES": {
        "WARD": 1.0,
        "CONSTITUENCY": 0.85,
        "COUNTY": 0.65,
        "DEFAULT": 0.45,
        "NO_LOCATION": 0.5,
    },

    "CONTENT_TYPE_SCORES": {
        "BALLOT": 0.95,
        "PETITION": 0.85,
        "BROADCAST": 0.80,
        "SURVEY": 0.75,
        "SECTION": 0.70,
        "DEFAULT": 0.40,
    },

    "MEDIA_SCORES": {
        "VIDEO": 0.95,
        "IMAGE": 0.85,
        "ANY_ASSET": 0.70,
        "DEFAULT": 0.35,
    },

    "FRESHNESS": {
        "RECENT_HOURS": 2,
        "DAY_HOURS": 24,
        "WEEK_HOURS": 168,
        "RECENT_SCORE": 1.0,
        "DAY_SCORE": 0.8,
        "WEEK_SCORE": 0.5,
        "OLD_SCORE": 0.2,
    },

    "SIMILARITY_SCORES": {
        "BALLOT": 0.75,
        "SURVEY": 0.75,
        "PETITION": 0.70,
        "BROADCAST": 0.80,
        "DEFAULT": 0.30,
    },

    "NOTE_QUALITY": {
        "MIN_HELPFUL_SCORE": 0.7,
    },
}

FOLLOW_RECOMMENDER_CONFIG = {
    "CACHE": {
        "KEY_PREFIX": "user_follow_recs_",
        "TIMEOUT": 60 * 60,  # 1 hour
    },

    "DEFAULT_LIMIT": 15,
    "SCORED_LIMIT": 80,
    "DIVERSITY_FACTOR": 0.10,

    # Final follow recommendation weights.
    # These should sum to 1.0.
    "WEIGHTS": {
        "location": 0.25,
        "mutual": 0.30,
        "profile_visit": 0.15,
        "engagement": 0.10,
        "recency": 0.15,
        "activity": 0.05,
    },

    "LOCATION_SCORES": {
        "WARD": 1.0,
        "CONSTITUENCY": 0.85,
        "COUNTY": 0.65,
        "DEFAULT": 0.45,
        "NO_LOCATION": 0.50,
    },

    "MUTUAL_SCORE_TIERS": [
        {"MIN_MUTUALS": 5, "SCORE": 1.0},
        {"MIN_MUTUALS": 3, "SCORE": 0.85},
        {"MIN_MUTUALS": 1, "SCORE": 0.65},
    ],

    "PROFILE_VISIT": {
        "SCORE": 0.85,
    },

    "RECENCY": {
        "ACTIVE_DAYS": 7,
        "ACTIVE_SCORE": 0.8,
        "SEMI_ACTIVE_DAYS": 30,
        "SEMI_ACTIVE_SCORE": 0.5,
        "DEFAULT_SCORE": 0.2,
    },

    # Engagement is normalized/capped so it cannot dominate the score.
    "ENGAGEMENT": {
        "LIKE_WEIGHT": 0.6,
        "CLICK_WEIGHT": 0.4,
        "CAP": 1.0,
    },

    # Activity is normalized/capped.
    # Example: 20 published posts => activity score of 1.0.
    "ACTIVITY": {
        "PUBLISHED_POST_CAP": 20,
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apps.broadcast': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apps.recommendations': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.channels': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        '': {  # root logger
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
