# Generated by Django 6.0.4 on 2026-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Follow Recommendation Cache',
                'db_table': 'FollowRecommendationCache',
            },
        ),
        migrations.CreateModel(
            name='PostRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_post_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Recommendation Cache',
                'db_table': 'PostRecommendationCache',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('click', 'Clicked'), ('like', 'Liked'), ('bookmark', 'Bookmarked'), ('reply', 'Replied'), ('repost', 'Reposted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserInteraction',
            },
        ),
    ]
