# Generated by Django 6.0.4 on 2026-04-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followrecommendationcache',
            name='recommended_users',
            field=models.ManyToManyField(blank=True, related_name='recommended_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrecommendationcache',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_recommendation_cache', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrecommendationcache',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_recommendation_cache', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'created_at'], name='UserInterac_user_id_5c0269_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['post', 'interaction_type'], name='UserInterac_post_id_817c9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'post', 'interaction_type')},
        ),
    ]
