# Generated by Django 6.0.4 on 2026-04-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('recommended_users', models.ManyToManyField(blank=True, related_name='recommended_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_recommendation_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow Recommendation Cache',
                'db_table': 'FollowRecommendationCache',
            },
        ),
        migrations.CreateModel(
            name='PostRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_post_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_recommendation_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Recommendation Cache',
                'db_table': 'PostRecommendationCache',
            },
        ),
        migrations.DeleteModel(
            name='RecommendationCache',
        ),
    ]
