# Generated by Django 6.0.4 on 2026-08-06 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postrecommendationcache',
            index=models.Index(fields=['user', 'generated_at'], name='PostRecomme_user_id_8380cb_idx'),
        ),
    ]
