# Generated by Django 6.0.4 on 2026-04-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_followrecommendationcache_postrecommendationcache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('click', 'Clicked'), ('like', 'Liked'), ('bookmark', 'Bookmarked'), ('reply', 'Replied'), ('repost', 'Reposted')], max_length=20),
        ),
    ]
