# Generated by Django 6.0.4 on 2026-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_userinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Viewed'), ('click', 'Clicked'), ('like', 'Liked'), ('bookmark', 'Bookmarked'), ('reply', 'Replied'), ('repost', 'Reposted')], max_length=20),
        ),
    ]
