# Generated by Django 6.0.4 on 2026-04-22 19:37

import apps.users.managers
import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('id_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('image', models.ImageField(default='defaults/user.jpg', upload_to=apps.users.models.UploadImageTo('profiles'))),
                ('cover_photo', models.ImageField(default='defaults/cover.jpg', upload_to=apps.users.models.UploadImageTo('cover_photos'))),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('blocked', models.ManyToManyField(blank=True, related_name='blockers', to=settings.AUTH_USER_MODEL)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.constituency')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.county')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('muted', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('notifiers', models.ManyToManyField(blank=True, related_name='notification_recipients', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.ward')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'User',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Visit',
                'verbose_name_plural': 'Profile Visits',
                'db_table': 'ProfileVisit',
                'ordering': ['-visited_at'],
                'unique_together': {('visitor', 'visited')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='profiles_visited', through='users.ProfileVisit', through_fields=('visitor', 'visited'), to=settings.AUTH_USER_MODEL),
        ),
    ]
