# Generated by Django 6.0.1 on 2026-04-09 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='profiles_visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
