# Generated by Django 6.0.1 on 2026-03-24 16:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='cover_photos/default.jpg', upload_to=apps.users.models.UploadImageTo('cover_photos/')),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=apps.users.models.UploadImageTo('images/')),
        ),
    ]
