# Generated by Django 6.0.4 on 2026-04-11 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifiers',
            field=models.ManyToManyField(blank=True, related_name='notification_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
