# Generated by Django 6.0.4 on 2026-04-11 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_notifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='visits',
        ),
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Visit',
                'verbose_name_plural': 'Profile Visits',
                'db_table': 'ProfileVisit',
                'ordering': ['-visited_at'],
                'unique_together': {('visitor', 'visited')},
            },
        ),
    ]
