# Generated by Django 6.0.4 on 2026-04-11 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_visits_profilevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='profiles_visited', through='users.ProfileVisit', through_fields=('visitor', 'visited'), to=settings.AUTH_USER_MODEL),
        ),
    ]
