# Generated by Django 6.0.1 on 2026-03-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0003_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
