# Generated by Django 6.0.4 on 2026-08-10 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('broadcast', '0002_initial'),
        ('chat', '0002_initial'),
        ('notification', '0004_initial'),
        ('petition', '0002_initial'),
        ('posts', '0002_initial'),
        ('survey', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'id'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_like', 'post', 'is_read'], name='notif_like_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_follow', 'is_read'], name='notif_follow_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_support', 'petition', 'is_read'], name='notif_support_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['chat', 'recipient', 'is_read'], name='notif_chat_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['message', 'is_read'], name='notif_message_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_follow', True), ('is_read', False)), fields=('recipient',), name='uniq_unread_follow_notif'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_like', True), ('is_read', False), ('post__isnull', False)), fields=('recipient', 'post'), name='uniq_unread_like_notif'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False), ('is_support', True), ('petition__isnull', False)), fields=('recipient', 'petition'), name='uniq_unread_support_notif'),
        ),
    ]
