# Generated by Django 6.0.4 on 2026-09-09 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_ballot_search_vector_ballot_ballot_search_vector_idx_and_more'),
        ('broadcast', '0005_broadcast_search_vector_and_more'),
        ('chat', '0002_initial'),
        ('notification', '0004_initial'),
        ('petition', '0003_petition_search_vector_and_more'),
        ('posts', '0004_post_post_body_trgm_idx'),
        ('survey', '0005_survey_search_vector_survey_survey_search_vector_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_follow_notif',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_like_notif',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_support_notif',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_like_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_follow_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_support_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('like', 'Like'), ('follow', 'Follow'), ('support', 'Support')], default='general', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'type', 'post', 'is_read'], name='notif_like_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'type', 'is_read'], name='notif_follow_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'type', 'petition', 'is_read'], name='notif_support_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False), ('type', 'follow')), fields=('recipient',), name='uniq_unread_follow_type_notif'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False), ('post__isnull', False), ('type', 'like')), fields=('recipient', 'post'), name='uniq_unread_like_type_notif'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False), ('petition__isnull', False), ('type', 'support')), fields=('recipient', 'petition'), name='uniq_unread_support_type_notif'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_follow',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_support',
        ),
    ]
