# Generated by Django 6.0.4 on 2026-04-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='allowed_users',
            new_name='allowed_authors',
        ),
    ]
