# Generated by Django 6.0.4 on 2026-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
