# Generated by Django 6.0.4 on 2026-04-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_rename_receiver_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='allowed_authors',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='muted_posts',
        ),
    ]
