# Generated by Django 6.0.4 on 2026-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_remove_notification_user_notification_is_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='allow_petition_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='allow_petition_supporter_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
