# Generated by Django 6.0.4 on 2026-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_preferences_allow_petition_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
