# Generated by Django 5.2.1 on 2025-09-30 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='listening_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
