# Generated by Django 5.2.1 on 2025-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_meeting_listeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
