# Generated by Django 5.2.1 on 2025-10-03 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_meeting_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='listening_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
