# Generated by Django 5.2.1 on 2025-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('text', models.TextField()),
                ('is_title', models.BooleanField()),
            ],
            options={
                'db_table': 'Section',
                'ordering': ['id', 'parent__position', 'position'],
            },
        ),
    ]
