# Generated by Django 6.0.1 on 2026-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0003_section_numeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='numeral',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
