# Generated by Django 5.2.1 on 2025-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0003_alter_section_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id', 'parent__position', 'position']},
        ),
    ]
