# Generated by Django 5.2.1 on 2025-05-26 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'IpAddress',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video1', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('video2', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('video3', models.ImageField(blank=True, null=True, upload_to='posts/videos/')),
                ('ip_address', models.GenericIPAddressField()),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('ip_views', models.ManyToManyField(blank=True, to='social.ipaddress')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.post')),
                ('user_views', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['-id'],
            },
        ),
    ]
