# Generated by Django 5.2.1 on 2025-05-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
