# Generated by Django 5.2.1 on 2025-06-14 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_post_is_repost_remove_post_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='post_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
