# Generated by Django 5.2.1 on 2025-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='o', max_length=255),
            preserve_default=False,
        ),
    ]
