# Generated by Django 5.2.1 on 2025-08-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-start_time']},
        ),
    ]
