# Generated by Django 5.2.1 on 2025-09-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='title',
        ),
    ]
