# Generated by Django 5.2.1 on 2025-07-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_reason_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-start_time']},
        ),
    ]
