# Generated by Django 6.0.4 on 2026-08-16 19:21

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Choice',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Page',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Response',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'Survey',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SurveySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('choice_stats', models.JSONField(blank=True, default=list)),
                ('number_stats', models.JSONField(blank=True, default=list)),
                ('text_themes', models.JSONField(blank=True, default=list)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('processed_text_answers', models.PositiveIntegerField(default=0)),
                ('sampled', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SurveySummary',
            },
        ),
        migrations.CreateModel(
            name='SurveyTextCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_cluster_id', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('centroid', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('representative_texts', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'SurveyTextCluster',
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('redacted_text', models.TextField(blank=True)),
                ('pii_entities', models.JSONField(blank=True, default=list)),
                ('pii_redacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TextAnswer',
            },
        ),
        migrations.CreateModel(
            name='TextAnswerEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                'db_table': 'TextAnswerEmbedding',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Number', 'Number'), ('Text', 'Text'), ('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice')], max_length=255)),
                ('text', models.TextField()),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='survey.choice')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.page')),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choice_answers', to='survey.question')),
            ],
            options={
                'db_table': 'ChoiceAnswer',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question'),
        ),
    ]
