# Generated by Django 6.0.4 on 2026-08-11 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='survey.response'),
        ),
        migrations.AddField(
            model_name='survey',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='survey',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='geo.county'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='geo.ward'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='page',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_answers', to='survey.question'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='survey.response'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='unique_choice_text_per_question'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'created_at'], name='Survey_is_acti_6ffa13_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['county'], name='Survey_county__581b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['constituency'], name='Survey_constit_1ab83b_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['ward'], name='Survey_ward_id_acc345_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('constituency__isnull', False), _connector='OR'), name='survey_ward_requires_constituency', violation_error_message='A ward requires a constituency.'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('county__isnull', False), _connector='OR'), name='survey_ward_requires_county', violation_error_message='A ward requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(condition=models.Q(('constituency__isnull', True), ('county__isnull', False), _connector='OR'), name='survey_constituency_requires_county', violation_error_message='A constituency requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='unique_response_per_survey_user'),
        ),
    ]
