# Generated by Django 6.0.1 on 2026-04-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'created_at'], name='Survey_is_acti_6ffa13_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['county'], name='Survey_county__581b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['constituency'], name='Survey_constit_1ab83b_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['ward'], name='Survey_ward_id_acc345_idx'),
        ),
    ]
