# Generated by Django 6.0.4 on 2026-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_add_text_answer_embedding_hnsw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
