# Generated by Django 6.0.4 on 2026-09-08 09:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('survey', '0004_alter_surveysummary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='survey_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('title'), name='gin_trgm_ops'), name='survey_title_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('description'), name='gin_trgm_ops'), name='survey_description_trgm_idx'),
        ),
    ]
