# Generated by Django 5.2.1 on 2025-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
