# Generated by Django 6.0.1 on 2026-03-29 12:07

import apps.posts.models
import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/'))),
                ('image2', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/'))),
                ('image3', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/'))),
                ('image4', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/'))),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadVideoTo('videos/'))),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadFileTo('files/'))),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
