# Generated by Django 6.0.4 on 2026-08-26 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_add_reason_embedding_hnsw'),
        ('broadcast', '0004_alter_comment_options_rename_content_comment_text_and_more'),
        ('constitution', '0001_initial'),
        ('petition', '0002_initial'),
        ('posts', '0002_initial'),
        ('survey', '0003_add_text_answer_embedding_hnsw'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='Post_publish_549d78_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', '-created_at'], name='Report_post_id_b7a20a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-updated_at'], name='SearchHisto_user_id_267c31_idx'),
        ),
    ]
