# Generated by Django 6.0.4 on 2026-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_type',
            field=models.CharField(blank=True, choices=[('repost', 'Repost'), ('quote', 'Quote')], max_length=10, null=True),
        ),
    ]
