# Generated by Django 6.0.1 on 2026-03-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('meeting', '0002_initial'),
        ('petition', '0002_initial'),
        ('posts', '0002_initial'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='ballot.ballot'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community_note_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_notes', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='posts/files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='petition.petition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='survey.survey'),
        ),
    ]
