# Generated by Django 6.0.1 on 2026-04-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
        ('posts', '0003_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='constitution.section'),
        ),
    ]
