# Generated by Django 6.0.1 on 2026-03-24 15:45

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_ballot_alter_post_community_note_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadFileTo('files/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadVideoTo('videos/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('videos/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to=apps.posts.models.UploadImageTo('videos/')),
        ),
    ]
