# Generated by Django 6.0.4 on 2026-09-08 09:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_ballot_search_vector_ballot_ballot_search_vector_idx_and_more'),
        ('broadcast', '0004_alter_comment_options_rename_content_comment_text_and_more'),
        ('constitution', '0001_initial'),
        ('petition', '0003_petition_search_vector_and_more'),
        ('posts', '0003_post_post_publish_549d78_idx_and_more'),
        ('survey', '0004_alter_surveysummary_status'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('body'), name='gin_trgm_ops'), name='post_body_trgm_idx'),
        ),
    ]
