# Generated by Django 6.0.4 on 2026-05-10 17:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('constitution', '0001_initial'),
        ('meeting', '0009_remove_meeting_participants'),
        ('petition', '0002_initial'),
        ('posts', '0003_post_hashtags'),
        ('survey', '0002_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Post_search__4c2299_gin'),
        ),
    ]
