# Generated by Django 6.0.1 on 2026-04-09 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
