# Generated by Django 6.0.1 on 2026-03-26 07:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_file_alter_post_image1_alter_post_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
