# Generated by Django 6.0.4 on 2026-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='muted'),
        ),
    ]
