# Generated by Django 6.0.4 on 2026-04-11 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_clicks_remove_post_likes_postclick_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicked_posts', through='posts.PostClick', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='posts.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
