# Generated by Django 6.0.4 on 2026-04-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_file_remove_post_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='posts.post'),
        ),
    ]
