# Generated by Django 6.0.4 on 2026-04-22 19:37

import apps.petition.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=apps.petition.models.UploadImageTo('images'))),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.petition.models.UploadVideoTo('videos'))),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True, verbose_name='open')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'Petition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Petition Click',
                'verbose_name_plural': 'Petition Clicks',
                'db_table': 'PetitionClick',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Petition Support',
                'verbose_name_plural': 'Petition Support',
                'db_table': 'PetitionSupport',
                'ordering': ['-supported_at'],
            },
        ),
    ]
