# Generated by Django 6.0.4 on 2026-08-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='petition',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.county'),
        ),
        migrations.AddField(
            model_name='petition',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.ward'),
        ),
        migrations.AddField(
            model_name='petitionclick',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_through', to='petition.petition'),
        ),
        migrations.AddField(
            model_name='petitionclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked_petitions_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicked_petitions', through='petition.PetitionClick', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petitionsupport',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters_through', to='petition.petition'),
        ),
        migrations.AddField(
            model_name='petitionsupport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_petitions_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', through='petition.PetitionSupport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='petitionclick',
            index=models.Index(fields=['petition', '-clicked_at'], name='PetitionCli_petitio_907d48_idx'),
        ),
        migrations.AddIndex(
            model_name='petitionclick',
            index=models.Index(fields=['user'], name='PetitionCli_user_id_128768_idx'),
        ),
        migrations.AddConstraint(
            model_name='petitionclick',
            constraint=models.UniqueConstraint(fields=('user', 'petition'), name='unique_petition_click'),
        ),
        migrations.AddIndex(
            model_name='petitionsupport',
            index=models.Index(fields=['petition', '-supported_at'], name='PetitionSup_petitio_e36b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='petitionsupport',
            index=models.Index(fields=['user'], name='PetitionSup_user_id_89a843_idx'),
        ),
        migrations.AddConstraint(
            model_name='petitionsupport',
            constraint=models.UniqueConstraint(fields=('user', 'petition'), name='unique_petition_support'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['is_active', 'is_open', '-created_at'], name='Petition_is_acti_4dc10b_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['author', '-created_at'], name='Petition_author__7bc36f_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['county', 'constituency', 'ward'], name='Petition_county__7253e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='petition',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('constituency__isnull', False), _connector='OR'), name='petition_ward_requires_constituency', violation_error_message='A ward requires a constituency.'),
        ),
        migrations.AddConstraint(
            model_name='petition',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('county__isnull', False), _connector='OR'), name='petition_ward_requires_county', violation_error_message='A ward requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='petition',
            constraint=models.CheckConstraint(condition=models.Q(('constituency__isnull', True), ('county__isnull', False), _connector='OR'), name='petition_constituency_requires_county', violation_error_message='A constituency requires a county.'),
        ),
    ]
