# Generated by Django 6.0.4 on 2026-04-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='petition',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.county'),
        ),
        migrations.AddField(
            model_name='petition',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.ward'),
        ),
        migrations.AddField(
            model_name='petitionclick',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_through', to='petition.petition'),
        ),
        migrations.AddField(
            model_name='petitionclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked_petitions_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicked_petitions', through='petition.PetitionClick', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petitionsupport',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters_through', to='petition.petition'),
        ),
        migrations.AddField(
            model_name='petitionsupport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_petitions_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', through='petition.PetitionSupport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='petitionclick',
            unique_together={('user', 'petition')},
        ),
        migrations.AlterUniqueTogether(
            name='petitionsupport',
            unique_together={('user', 'petition')},
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['is_open', 'is_active', 'created_at'], name='Petition_is_open_12aa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['author'], name='Petition_author__9e4671_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['county'], name='Petition_county__9a62fb_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['constituency'], name='Petition_constit_a33312_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['ward'], name='Petition_ward_id_b0ebde_idx'),
        ),
    ]
