# Generated by Django 6.0.1 on 2026-03-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='petition',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.county'),
        ),
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='geo.ward'),
        ),
    ]
