# Generated by Django 6.0.1 on 2026-03-24 16:26

import apps.petition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=models.ImageField(upload_to=apps.petition.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='petition',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.petition.models.UploadVideoTo('videos/')),
        ),
    ]
