# Generated by Django 6.0.1 on 2026-04-08 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('petition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['is_open', 'is_active', 'created_at'], name='Petition_is_open_12aa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['author'], name='Petition_author__9e4671_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['county'], name='Petition_county__9a62fb_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['constituency'], name='Petition_constit_a33312_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['ward'], name='Petition_ward_id_b0ebde_idx'),
        ),
    ]
