# Generated by Django 6.0.4 on 2026-04-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_petition_petition_is_open_12aa2a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='supporters',
        ),
    ]
