# Generated by Django 6.0.4 on 2026-04-13 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_remove_petition_supporters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PetitionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_through', to='petition.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked_petitions_through', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petition Click',
                'verbose_name_plural': 'Petition Clicks',
                'db_table': 'PetitionClick',
                'ordering': ['-clicked_at'],
                'unique_together': {('user', 'petition')},
            },
        ),
        migrations.AddField(
            model_name='petition',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicked_petitions', through='petition.PetitionClick', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PetitionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters_through', to='petition.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_petitions_through', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petition Support',
                'verbose_name_plural': 'Petition Support',
                'db_table': 'PetitionSupport',
                'ordering': ['-supported_at'],
                'unique_together': {('user', 'petition')},
            },
        ),
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', through='petition.PetitionSupport', to=settings.AUTH_USER_MODEL),
        ),
    ]
