# Generated by Django 6.0.4 on 2026-08-11 08:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
                'db_table': 'County',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='County_name_99fc13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='geo.county')),
            ],
            options={
                'verbose_name': 'constituency',
                'verbose_name_plural': 'constituencies',
                'db_table': 'Constituency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='geo.constituency')),
            ],
            options={
                'verbose_name': 'ward',
                'verbose_name_plural': 'wards',
                'db_table': 'Ward',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['county', 'name'], name='Constituenc_county__77359a_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['constituency', 'name'], name='Ward_constit_91f174_idx'),
        ),
    ]
