# Generated by Django 6.0.4 on 2026-04-13 14:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_constituency_boundaries_constituency_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='center',
        ),
        migrations.AddField(
            model_name='ward',
            name='boundaries',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
