# Generated by Django 6.0.4 on 2026-09-23 10:31

import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('livestream', 'Livestream')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Broadcast',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'BroadcastComment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=255)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('file_list', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In progress'), ('stopped', 'Stopped'), ('error', 'Error')], default='in progress', max_length=50)),
            ],
            options={
                'db_table': 'RecordingSession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('co-host', 'Co-Host'), ('speaker', 'Speaker')], default='speaker', max_length=50)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SpeakerInvite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SpeakerRequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
