# Generated by Django 6.0.4 on 2026-08-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcast', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='co_hosts',
            field=models.ManyToManyField(blank=True, related_name='host_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='geo.constituency'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='geo.county'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaker_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='geo.ward'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='broadcast.broadcast'),
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_sessions', to='broadcast.broadcast'),
        ),
        migrations.AddField(
            model_name='speakerrequest',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_requests', to='broadcast.broadcast'),
        ),
        migrations.AddField(
            model_name='speakerrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_request_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speakerrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['type', 'is_active'], name='Broadcast_type_f8117d_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['start_time'], name='Broadcast_start_t_bf4060_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['end_time'], name='Broadcast_end_tim_174389_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['host'], name='Broadcast_host_id_194ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['county'], name='Broadcast_county__a6430f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['constituency'], name='Broadcast_constit_948781_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['ward'], name='Broadcast_ward_id_e94566_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='broadcast_end_time_after_start_time', violation_error_message='The end time must be after the start time.'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['meeting', 'livestream'])), name='broadcast_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('constituency__isnull', False), _connector='OR'), name='broadcast_ward_requires_constituency', violation_error_message='A ward requires a constituency.'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('ward__isnull', True), ('county__isnull', False), _connector='OR'), name='broadcast_ward_requires_county', violation_error_message='A ward requires a county.'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('constituency__isnull', True), ('county__isnull', False), _connector='OR'), name='broadcast_constituency_requires_county', violation_error_message='A constituency requires a county.'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['broadcast', 'stopped_at'], name='RecordingSe_broadca_7d1f91_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['status'], name='RecordingSe_status_b099a4_idx'),
        ),
        migrations.AddIndex(
            model_name='speakerrequest',
            index=models.Index(fields=['broadcast', 'is_approved'], name='SpeakerRequ_broadca_e56879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerrequest',
            unique_together={('broadcast', 'user')},
        ),
    ]
