# Generated by Django 6.0.4 on 2026-06-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='is_recorded',
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('livestream', 'Livestream')], max_length=10),
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('broadcast', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='broadcast.broadcast')),
            ],
            options={
                'db_table': 'RecordingSession',
                'ordering': ['-created_at'],
            },
        ),
    ]
