# Generated by Django 6.0.4 on 2026-08-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('co-host', 'Co-Host'), ('speaker', 'Speaker')], default='speaker', max_length=50)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SpeakerInvite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='speakerrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='speakerrequest',
            constraint=models.UniqueConstraint(fields=('broadcast', 'user'), name='unique_speaker_request'),
        ),
        migrations.AddField(
            model_name='speakerinvite',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_invites', to='broadcast.broadcast'),
        ),
        migrations.AddField(
            model_name='speakerinvite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='speakerinvite',
            index=models.Index(fields=['broadcast', 'is_accepted'], name='SpeakerInvi_broadca_e80909_idx'),
        ),
        migrations.AddConstraint(
            model_name='speakerinvite',
            constraint=models.UniqueConstraint(fields=('broadcast', 'user'), name='unique_speaker_invite'),
        ),
    ]
