# Generated by Django 6.0.4 on 2026-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_remove_broadcast_is_recorded_alter_broadcast_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='file_key',
            field=models.CharField(default=0, max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
