# Generated by Django 6.0.4 on 2026-08-26 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_speakerinvite_alter_speakerrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['broadcast', '-created_at'], name='BroadcastCo_broadca_124297_idx'),
        ),
    ]
