# Generated by Django 6.0.4 on 2026-09-08 09:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_alter_comment_options_rename_content_comment_text_and_more'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='broadcast_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('title'), name='gin_trgm_ops'), name='broadcast_title_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('description'), name='gin_trgm_ops'), name='broadcast_description_trgm_idx'),
        ),
    ]
