# Generated by Django 6.0.4 on 2026-06-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0006_alter_recordingsession_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='broadcast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='broadcast.broadcast'),
        ),
    ]
