# Generated by Django 6.0.4 on 2026-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0007_alter_recordingsession_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
