# Generated by Django 6.0.4 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0008_recordingsession_stopped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='file_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='status',
            field=models.CharField(choices=[('in progress', 'In progress'), ('stopped', 'Stopped'), ('error', 'Error')], default='in progress', max_length=50),
        ),
    ]
