# Generated by Django 6.0.4 on 2026-06-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0009_recordingsession_file_list_recordingsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordingsession',
            name='file_key',
        ),
    ]
