# Generated by Django 6.0.4 on 2026-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0010_remove_recordingsession_file_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='resource_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='sid',
            field=models.CharField(max_length=255),
        ),
    ]
