# Generated by Django 6.0.4 on 2026-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0011_alter_recordingsession_resource_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='file_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
