# Generated by Django 5.2.1 on 2025-05-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_alter_question_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='Choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='response',
            table='Response',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='Survey',
        ),
    ]
