# Generated by Django 5.2.1 on 2025-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_alter_survey_options_alter_answer_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='survey',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Number', 'Number'), ('Text', 'Text'), ('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice')], max_length=255),
        ),
    ]
