# Generated by Django 6.0.1 on 2026-03-29 12:07

import apps.chat.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/'))),
                ('image2', models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/'))),
                ('image3', models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/'))),
                ('image4', models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/'))),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.chat.models.UploadVideoTo('videos/'))),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chat.models.UploadFileTo('files/'))),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['-created_at'],
            },
        ),
    ]
