# Generated by Django 6.0.1 on 2026-04-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='constitution.section'),
        ),
    ]
