# Generated by Django 6.0.4 on 2026-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
