# Generated by Django 6.0.1 on 2026-03-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_initial'),
        ('chat', '0002_initial'),
        ('meeting', '0002_initial'),
        ('petition', '0002_initial'),
        ('posts', '0002_initial'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='ballot.ballot'),
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='message',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='petition.petition'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='survey.survey'),
        ),
    ]
