# Generated by Django 6.0.4 on 2026-04-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
    ]
