# Generated by Django 6.0.1 on 2026-03-24 15:38

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_ballot_alter_message_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.chat.models.UploadFileTo('files/')),
        ),
        migrations.AlterField(
            model_name='message',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='message',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='message',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/')),
        ),
        migrations.AlterField(
            model_name='message',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chat.models.UploadImageTo('images/')),
        ),
    ]
