# Generated by Django 6.0.4 on 2026-04-21 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_user_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('content_type', models.CharField(help_text='e.g., image/jpeg', max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='chat.message')),
            ],
            options={
                'db_table': 'MessageAsset',
            },
        ),
    ]
