# Generated by Django 6.0.1 on 2026-03-26 07:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_file_alter_message_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
